package models

// Code generated by dbtpl. DO NOT EDIT.

import (
	"context"
	"time"
)

// FnRollbackAudit calls the stored function 'public.fn_rollback_audit(audited_table_enum, integer, integer, timestamp with time zone)' on db.
func FnRollbackAudit(ctx context.Context, db DB, pTable AuditedTableEnum, pStore, pUser int, pToTs time.Time) error {
	// call public.fn_rollback_audit
	const sqlstr = `SELECT * FROM public.fn_rollback_audit($1, $2, $3, $4)`
	// run
	logf(sqlstr)
	if _, err := db.ExecContext(ctx, sqlstr, pTable, pStore, pUser, pToTs); err != nil {
		return logerror(err)
	}
	return nil
}
