package models

// Code generated by dbtpl. DO NOT EDIT.

import (
	"context"
)

// FnAuditGeneric calls the stored function 'public.fn_audit_generic() trigger' on db.
func FnAuditGeneric(ctx context.Context, db DB) (Trigger, error) {
	// call public.fn_audit_generic
	const sqlstr = `SELECT * FROM public.fn_audit_generic()`
	// run
	var r0 Trigger
	logf(sqlstr)
	if err := db.QueryRowContext(ctx, sqlstr).Scan(&r0); err != nil {
		return Trigger{}, logerror(err)
	}
	return r0, nil
}
