package models

// Code generated by dbtpl. DO NOT EDIT.

import (
	"context"
)

// UserRole represents a row from 'public.user_roles'.
type UserRole struct {
	UserID int `json:"user_id"` // user_id
	RoleID int `json:"role_id"` // role_id
	// xo fields
	_exists, _deleted bool
}

// Exists returns true when the [UserRole] exists in the database.
func (ur *UserRole) Exists() bool {
	return ur._exists
}

// Deleted returns true when the [UserRole] has been marked for deletion
// from the database.
func (ur *UserRole) Deleted() bool {
	return ur._deleted
}

// Insert inserts the [UserRole] to the database.
func (ur *UserRole) Insert(ctx context.Context, db DB) error {
	switch {
	case ur._exists: // already exists
		return logerror(&ErrInsertFailed{ErrAlreadyExists})
	case ur._deleted: // deleted
		return logerror(&ErrInsertFailed{ErrMarkedForDeletion})
	}
	// insert (manual)
	const sqlstr = `INSERT INTO public.user_roles (` +
		`user_id, role_id` +
		`) VALUES (` +
		`$1, $2` +
		`)`
	// run
	logf(sqlstr, ur.UserID, ur.RoleID)
	if _, err := db.ExecContext(ctx, sqlstr, ur.UserID, ur.RoleID); err != nil {
		return logerror(err)
	}
	// set exists
	ur._exists = true
	return nil
}

// ------ NOTE: Update statements omitted due to lack of fields other than primary key ------

// Delete deletes the [UserRole] from the database.
func (ur *UserRole) Delete(ctx context.Context, db DB) error {
	switch {
	case !ur._exists: // doesn't exist
		return nil
	case ur._deleted: // deleted
		return nil
	}
	// delete with composite primary key
	const sqlstr = `DELETE FROM public.user_roles ` +
		`WHERE user_id = $1 AND role_id = $2`
	// run
	logf(sqlstr, ur.UserID, ur.RoleID)
	if _, err := db.ExecContext(ctx, sqlstr, ur.UserID, ur.RoleID); err != nil {
		return logerror(err)
	}
	// set deleted
	ur._deleted = true
	return nil
}

// UserRoleByUserIDRoleID retrieves a row from 'public.user_roles' as a [UserRole].
//
// Generated from index 'user_roles_pkey'.
func UserRoleByUserIDRoleID(ctx context.Context, db DB, userID, roleID int) (*UserRole, error) {
	// query
	const sqlstr = `SELECT ` +
		`user_id, role_id ` +
		`FROM public.user_roles ` +
		`WHERE user_id = $1 AND role_id = $2`
	// run
	logf(sqlstr, userID, roleID)
	ur := UserRole{
		_exists: true,
	}
	if err := db.QueryRowContext(ctx, sqlstr, userID, roleID).Scan(&ur.UserID, &ur.RoleID); err != nil {
		return nil, logerror(err)
	}
	return &ur, nil
}
